##server.port	                       应用程序启动端口	server.port=8080，定义应用程序启动端口为 8080
#server.servlet.context-path	      应用程序上下文	server.servlet.context-path=/api，则访问地址为：http://ip:port/api
#spring.servlet.multipart.maxFileSize	最大文件上传大小，-1为不限制	spring.servlet.multipart.maxFileSize=-1
#spring.jpa.database	               数据库类型	spring.jpa.database=MYSQL，指定数据库为mysql
#spring.jpa.properties.hibernate.dialect	hql方言	spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#spring.datasource.url	               数据库连接字符串	spring.datasource.url=jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=UTF-8&useSSL=true
#spring.datasource.username	             数据库用户名	spring.datasource.username=root
#spring.datasource.password	           数据库密码	spring.datasource.password=root
#spring.datasource.driverClassName	      数据库驱动	spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.jpa.showSql	              控制台是否打印 SQL 语句	spring.jpa.showSql=true

server:
  port:
    8080
#  servlet:
#      context-path: /api

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server

